<?php

namespace AppBundle\Entity;

use FOS\UserBundle\Model\UserInterface;

/**
 * repoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class repoRepository extends \Doctrine\ORM\EntityRepository {

	/**
	 * Gets Comments for a user
	 *
	 * @return array
	 */
	public function getCommentsforUser( $repositoryId, UserInterface $user ) {
		return $this->createQueryBuilder( 'r' )
		            ->select( 'c.body, c.date' )
		            ->join( 'r.comments', 'c', 'WITH', 'c.user = :user' )->setParameter( 'user', $user )
		            ->where( 'r.id = :id' )->setParameter( 'id', $repositoryId )
		            ->getQuery()
		            ->getResult();
	}
}
